### ISSUE TITLE
Question about initialization.

### ISSUE THREAD

**Issue by junseokoh1** [UCSB-NLP-Chang/DiffusionDisentanglement#2]
Hi, thanks for your great work.
When I read your paper, I have question about initialization value of $$\lambda_t$$
As paper keep saying, it is reasonable to initialize lambda with 0.0 when T is large.

Is there any reason that you initialize lambda with 1.2?
Is it similar with negative prompt?

![image](https://user-images.githubusercontent.com/28286337/223327652-6581ae0e-219a-4b47-814d-ca1df93cfa4b.png)

I'd appreciate it if you could leave a comment.

**Comment by wuqiuche** [comment]
Hi @junseokoh1 , Thank you very much for your questions. You are correct - when $t$ is small, setting $\lambda_t$ to 1.2 means we have negative coefficient (-0.2) for $c^{(0)}$. Empirically, we find that this initialization provides a better starting point to optimize $\lambda_t$.
