### ISSUE TITLE
Question about optimization steps.

### ISSUE THREAD

**Issue by SherryXTChen** [UCSB-NLP-Chang/DiffusionDisentanglement#4]
Thank you for your great work. I have some questions regarding the optimization steps. 

From [here](https://github.com/UCSB-NLP-Chang/DiffusionDisentanglement/blob/main/ldm/models/diffusion/plms.py#L1040), it looks like only 10 optimization steps are used. Why do you set it to such a small number? How much do lambda's change after optimization? Do you see any pattern of how lambda changes across samples?

**Comment by wuqiuche** [comment]
Hi SherryXTChen,

Thank you for your interests in our work! We choose to use 10 optimization steps to balance between the editing effects and running efficiency. Empirically, we find 10 steps would be generally enough to have the disentangle effects. Increasing the optimization steps could lead to a clearer editing effects leveraging the combination of content preserve loss and CLIP loss.

Regarding the lambda's change after optimization, it varies across different samples, but we observe in general that the later timestamps tend to be more unstable and have a larger change. Also, a general observation is lambda tends to be higher at earlier steps and lower at later steps. This phenomenon could be observed clearer if all lambda is initialized at 0, and it also motivates us to initialize the lambda as shown in the paper.

Hope this helps!

**Comment by SherryXTChen** [comment]
Thank you!
