### ISSUE TITLE
GPU Memory needed for training

### ISSUE THREAD

**Issue by zelaki** [UCSB-NLP-Chang/DiffusionDisentanglement#6]
Thank you for your interesting work.
 I have a question regarding the GPU memory size you used for training.
I tried to run disentangle.py with an NVIDIA RTX-3090 GPU with 24GB of memory and got an out-of-memory error.

Thank you in advance,
Thodoris

**Comment by wuqiuche** [comment]
Hi Thodoris,

Thank you very much for your interest to our work! Unfortunately, as described [here](https://github.com/UCSB-NLP-Chang/DiffusionDisentanglement#requirements), this project requires a GPU memory of 48GB. You might want to try with a larger GPU. Sorry for the inconvenience!

Sincerely,
Qiucheng

**Comment by zelaki** [comment]
Hello Qiucheng, 
I was looking for that info in the paper and didn't look at your README. 
Thank you very much!
Thodoris
