### ISSUE TITLE
GPU Memory allocation error

### ISSUE THREAD

**Issue by TrickyJustice** [UCSB-NLP-Chang/DiffusionDisentanglement#8]
Hello authors,
I am trying to reproduce the results and I am facing the following error:

Traceback (most recent call last):
  File "scripts/disentangle.py", line 154, in <module>
    final_disentangle_attributes(opt)
  File "scripts/disentangle.py", line 78, in final_disentangle_attributes
    sampler.sample_optimize_intrinsic(
  File "/u1/a2soni/DiffusionDisentanglement/ldm/models/diffusion/plms.py", line 1222, in sample_optimize_intrinsic
    self.plms_sampling_optimize_intrinsic(
  File "/u1/a2soni/DiffusionDisentanglement/ldm/models/diffusion/plms.py", line 1437, in plms_sampling_optimize_intrinsic
    loss.backward()
  File "/u1/a2soni/.conda/envs/ldm/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/u1/a2soni/.conda/envs/ldm/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/u1/a2soni/.conda/envs/ldm/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/u1/a2soni/DiffusionDisentanglement/ldm/modules/diffusionmodules/util.py", line 139, in backward
    input_grads = torch.autograd.grad(
  File "/u1/a2soni/.conda/envs/ldm/lib/python3.8/site-packages/torch/autograd/__init__.py", line 275, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 47.51 GiB total capacity; 39.31 GiB already allocated; 826.50 MiB free; 44.71 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I am working on A6000 Ada with 48GB VRAM. Could you possibly help me with this? I also tried running on A100 with 40GB VRAM and it faces similar error except the main error is:

RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 39.59 GiB total capacity; 37.41 GiB already allocated; 108.19 MiB free; 37.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by wuqiuche** [comment]
Hi TrickyJustice,

Thank you very much for your interest! During optimizing, the code will need  about 42-46GB GPU memory on our machine, so A100 40GB won't work. However, it should be able to run on your A6000 48GB GPU. From your error message, I noticed the allocated memory (39.31GB) is somehow smaller than reserved memory (44.71GB) by 5.4GB. If possible, can you try reduce the max_split_size_mb on your side? For example, run
`export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'`
before running this repo (https://stackoverflow.com/questions/73747731/runtimeerror-cuda-out-of-memory-how-can-i-set-max-split-size-mb).

Besides, making sure there is no other programs take use of the GPU - the memory should be barely enough. Sorry for the inconvenience. Please let us know if this fix the issue if possible. Thank you again!

**Comment by TrickyJustice** [comment]
`export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'` Worked. Thanks

**Comment by TrickyJustice** [comment]
Could you also tell what's the minimum split size that we can use for this work? Can I go below 512? I will try doing it myselves and update it if I do it before you.
Thanks

**Comment by wuqiuche** [comment]
Thank you for confirming that this works on your end!

Based on my understanding, the split size is used to control the memory fragment size on the GPU. This feature is not a part of our implementation but rather a part of the CUDA implementation. A smaller split size could potentially reduce the chances of encountering the 'reserved memory is >> allocated memory' issue, as indicated in your previous log (and therefore might be _better_ in your case). However, if the split size is too small, it might impact efficiency, but experimenting with this could be definitely helpful.
